platform: x64

environment:
    matrix:
    # MinGW-w64
    - GENERATOR: MinGW Makefiles
      CXXFLAGS: -std=c++11
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration:
  - Debug
  - Release

branches:
  only:
    - master
    - develop

build_script:
  - set
  - mkdir build
  - cd build
  - cmake --version
  - echo cmake -G "%GENERATOR%" ..
  - echo cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION%